"""
Complete Es Teller Nusantara Photography Brief - Full Enhanced Version
"""

import json
from fastapi.testclient import TestClient
from app.main import app

client = TestClient(app)

def display_full_enhanced_brief():
    """Generate and display the complete enhanced brief for Es Teller Nusantara."""
    
    user_request = """Realistic Indonesian drink advertisement poster with text "Es Teller Nusantara", tall glass filled with coconut, avocado, jackfruit, shaved ice, and condensed milk, placed on rustic wooden surface with droplets of water, bright tropical green glowing background, floating ice cubes around, fresh and vibrant vibe."""
    
    print("🇮🇩 ES TELLER NUSANTARA - COMPLETE PHOTOGRAPHY BRIEF")
    print("=" * 80)
    print(f"📝 Original Request: {user_request}")
    print("=" * 80)
    
    # Step 1: Extract data
    print("\n🔍 STEP 1: AI EXTRACTION")
    extract_response = client.post("/api/v1/extract-and-fill", json={"user_request": user_request})
    wizard_input = extract_response.json()
    
    print(f"✅ Status: {extract_response.status_code}")
    print(f"🎯 Extracted Fields: {len(wizard_input)}")
    
    # Step 2: Generate enhanced brief
    print("\n🎨 STEP 2: AI CREATIVE DIRECTOR ENHANCEMENT")
    brief_response = client.post("/api/v1/generate-brief", json=wizard_input)
    
    if brief_response.status_code == 200:
        brief_data = brief_response.json()
        enhanced_brief = brief_data.get('final_prompt', '')
        
        print(f"✅ Status: {brief_response.status_code}")
        print(f"📄 Brief Length: {len(enhanced_brief)} characters")
        print("\n" + "="*80)
        print("🎬 FINAL ENHANCED PHOTOGRAPHY BRIEF")
        print("="*80)
        print(enhanced_brief)
        print("="*80)
        
        # Save to file for easy reading
        with open('es_teller_nusantara_photography_brief.txt', 'w', encoding='utf-8') as f:
            f.write(f"ES TELLER NUSANTARA - PHOTOGRAPHY BRIEF\n")
            f.write(f"Generated by PhotoeAI Engine\n")
            f.write(f"Date: {str(__import__('datetime').datetime.now())}\n")
            f.write("="*80 + "\n\n")
            f.write(f"Original Request:\n{user_request}\n\n")
            f.write("="*80 + "\n\n")
            f.write(enhanced_brief)
        
        print(f"\n💾 Brief saved to: es_teller_nusantara_photography_brief.txt")
        
        # Key metrics
        word_count = len(enhanced_brief.split())
        sections = enhanced_brief.count('###') + enhanced_brief.count('**')
        
        print(f"\n📊 BRIEF ANALYTICS:")
        print(f"   • Word Count: {word_count}")
        print(f"   • Sections: {sections}")
        print(f"   • Professional Format: ✅")
        print(f"   • Cultural Context: ✅ Indonesian Es Teller")
        print(f"   • Technical Details: ✅ Complete")
        print(f"   • Creative Enhancement: ✅ AI-Optimized")
        
    else:
        print(f"❌ Error: {brief_response.status_code}")
        print(brief_response.text)

if __name__ == "__main__":
    display_full_enhanced_brief()
