#!/usr/bin/env python3
"""
Direct watermelon juice extraction test - bypasses HTTP server
"""

import asyncio
import sys
import os

# Add the app directory to Python path
sys.path.append(os.path.join(os.path.dirname(__file__), '.'))

from app.schemas.models import InitialUserRequest
from app.services.brief_orchestrator import BriefOrchestratorService

async def test_watermelon_direct():
    """Test watermelon juice extraction directly via service calls"""
    
    print("🍉 WATERMELON JUICE ADVERTISEMENT - DIRECT TEST")
    print("=" * 80)
    
    # Initialize the service
    print("🔧 Initializing BriefOrchestratorService...")
    orchestrator = BriefOrchestratorService()
    
    # Create the user request
    user_request = InitialUserRequest(
        user_request="Create a vibrant tropical drink advertisement featuring a large watermelon juice bottle in the center. The bottle should appear big, glossy, and labeled 'WATERMELON JUICE – SUMMER FRESH.' Place a glass of watermelon juice beside it. Surround the bottle with watermelon slices, cubes, and whole mini watermelons floating around. Add a splash of red juice splattering around the bottle. The background should include a sunny tropical beach or palm trees, with blue sky and bright light rays. Include ice cubes, water droplets, and sparkles to give a fresh, lively effect."
    )
    
    print(f"\n📝 User Request: {user_request.user_request[:100]}...")
    
    try:
        # Step 1: Extract and autofill
        print("\n🔍 STEP 1: Extracting structured data...")
        wizard_input = await orchestrator.extract_and_autofill(user_request)
        print("✅ Extraction successful!")
        print(f"📊 Extracted {len(wizard_input.model_dump())} fields")
        
        # Show some key fields
        print("\n🎯 Key Extracted Fields:")
        data = wizard_input.model_dump()
        for key in ['main_subject', 'shot_type', 'camera_angle', 'lighting_style', 'background']:
            if key in data:
                value = data[key]
                if isinstance(value, str) and len(value) > 80:
                    value = value[:80] + "..."
                print(f"  {key}: {value}")
        
        # Step 2: Generate enhanced brief
        print("\n🎨 STEP 2: Generating enhanced photography brief...")
        brief_output = await orchestrator.generate_final_brief(wizard_input)
        print("✅ Enhanced brief generated successfully!")
        
        print(f"📝 Brief length: {len(brief_output.final_prompt)} characters")
        print(f"📊 Word count: ~{len(brief_output.final_prompt.split())} words")
        
        # Save the complete brief
        filename = "watermelon_juice_photography_brief.txt"
        from datetime import datetime
        timestamp = datetime.now().isoformat()
        
        with open(filename, 'w', encoding='utf-8') as f:
            f.write("WATERMELON JUICE - PHOTOGRAPHY BRIEF\n")
            f.write("Generated by PhotoeAI Engine\n")
            f.write(f"Date: {timestamp}\n")
            f.write("=" * 80 + "\n\n")
            f.write(f"Original Request:\n{user_request.user_request}\n\n")
            f.write("=" * 80 + "\n\n")
            f.write(brief_output.final_prompt)
        
        print(f"💾 Complete brief saved to: {filename}")
        
        # Show preview
        print("\n📋 ENHANCED BRIEF PREVIEW (First 400 characters):")
        print("-" * 60)
        print(brief_output.final_prompt[:400] + "...")
        print("-" * 60)
        
        return True
        
    except Exception as e:
        print(f"❌ Error during direct testing: {e}")
        import traceback
        traceback.print_exc()
        return False

if __name__ == "__main__":
    print("🚀 Starting direct PhotoeAI workflow test...")
    success = asyncio.run(test_watermelon_direct())
    
    if success:
        print("\n🎉 WATERMELON JUICE WORKFLOW TEST COMPLETED SUCCESSFULLY! 🎉")
        print("📄 The complete enhanced photography brief has been saved to file.")
        print("🔥 PhotoeAI dual-LLM architecture working perfectly!")
    else:
        print("\n💥 Test failed - check error details above")
